workers_dev = true
name = "my-worker"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
BETTER_AUTH_SECRET = "secret" # this would be stored as a secret, obviously.
BETTER_AUTH_URL = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "your-database-id"
migrations_dir = "drizzle"
